### PR TITLE
update Id and label in Section purger annotation

### LINKED ISSUE #3: Update plugin annotation for SectionPurger and SectionBundledPurger
The id, label, and description for these Purge plugins should be updated to indicate they are for section rather than the default http purger and so that they don't conflict.

### PR DESCRIPTION
**Pull request by aschreck**
This is to avoid potential naming conflicts with other purgers. Fixes #3

### CODE REVIEW

**Review by niccolox — APPROVED** [review]
does this need to go deeper with function names etc?

**Comment by aschreck** [comment]
do you have anything in mind in particular @niccolox ?

**Comment by niccolox** [comment]
no, open question, probably won't become an issue. 

Highly unlikely 2 CDNs will be running on a single app.

**Comment by aschreck** [comment]
This fix will make everything work properly even in the event of multiple CDNs

**Pull request merged**
